name: Comment JIRA issue number on PR
author: Sayam Hussain <sayam@momentumdash.com>
description: Leaves a JIRA issue number as a comment on a PR
branding:
  icon: 'message-square'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
